tap "gromgit/brewtils"
tap "guumaster/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "jstkdng/programs"
tap "kardolus/chatgpt-cli"
tap "koekeishiya/formulae"
tap "mongodb/brew"
tap "nikitabobko/tap"
tap "noahgorstein/tap"
tap "oven-sh/bun"
tap "plutov/tap"
cask "oq"
tap "rockymadden/rockymadden"
tap "samtay/tui"
tap "thefox/brewery"
tap "ymtdzzz/tap"
mas "Manet", id: 6470928235
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Cryptographic recipes and primitives for Python
brew "cryptography"
# Easily download, build, install, upgrade, and uninstall Python packages
brew "python-setuptools"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Automate deployment, configuration, and upgrading
brew "ansible@8"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# C library implementing the SSH2 protocol
brew "libssh2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# OpenAI's coding agent that runs in your terminal
brew "codex"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Run arbitrary commands when files change
brew "entr"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Blu-Ray disc playback library for media players like VLC
brew "libbluray"
# Light HTTP/1.1 server library
brew "libmicrohttpd"
# VP8/VP9 video codec
brew "libvpx"
# Secure Reliable Transport
brew "srt"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# Program for calculating and printing calendars
brew "gcal"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Automatic git commit --fixup
brew "git-absorb"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git extension for versioning large files
brew "git-lfs"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Library access to GnuPG
brew "gpgme"
# Tool for glamorous shell scripts
brew "gum"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Image loading and rendering library
brew "imlib2"
# Lightweight and flexible command-line JSON processor
brew "jq"
# TUI playground to experiment and play with jq
brew "jqp"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Simple terminal UI for git commands
brew "lazygit"
# X.Org: X Toolkit Intrinsics library
brew "libxt"
# Powerful, lightweight programming language
brew "lua"
# Terminal image, video, directory, and Markdown viewer
brew "mcat"
# Intercept, modify, replay, save HTTP/S traffic
brew "mitmproxy"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# NCurses Disk Usage
brew "ncdu"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Password manager
brew "pass"
# Process Management Interface for HPC environments
brew "pmix"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Terminal slideshow tool
brew "presenterm"
# Python version management
brew "pyenv"
# Database management TUI for PostgreSQL/MySQL/SQLite
brew "rainfrog"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Command-line time tracking application
brew "timewarrior"
# Terminal multiplexer
brew "tmux"
# Command-line interface for Vercel
brew "vercel-cli"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
brew "z"
brew "koekeishiya/formulae/skhd"
brew "oven-sh/bun/bun"
cask "1password"
cask "1password-cli"
cask "aerospace"
cask "arduino-ide"
cask "bambu-studio"
cask "bruno"
cask "espanso"
cask "font-hack-nerd-font"
cask "font-mononoki-nerd-font"
cask "ghostty"
cask "gimp"
cask "glide-browser"
cask "kdenlive"
cask "keycastr"
cask "keymapp"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "netnewswire"
cask "ngrok"
cask "obs"
cask "obsidian"
cask "openscad"
cask "polypane"
cask "soulseek"
cask "steam"
cask "syntax-highlight"
cask "telegram"
cask "transmission"
cask "vivaldi"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/ramya-rao-a/go-outline"
go "github.com/fatih/gomodifytags"
go "github.com/haya14busa/goplay/cmd/goplay"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "github.com/josharian/impl"
go "github.com/szktkfm/mdtt/cmd/mdtt"
go "github.com/guyfedwards/nom/cmd/nom"
go "honnef.co/go/tools/cmd/staticcheck"
